name: Test workflow
run-name: test workflow of ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      greeting_name:
        required: true
        type: string
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello ${{ inputs.greeting_name }}"
      - name: List packages
        run: apt list --installed
